bin.includes = META-INF/,\
               .,\
               src/,\
               web/,\
               migration/,\
               OSGI-INF/requestkanban_form_factory.xml
source.. = src/
output.. = bin/
